# Generated by Django 3.0.3 on 2020-02-08 05:39

import PortalUser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalUser', '0002_auto_20200207_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to=PortalUser.models.user_directory_path),
        ),
    ]
